Django==1.8.7
five==0.4.0
six==1.10.0
django-cuser==2017.3.16
django-model-utils==3.0.0
pyshp==1.2.12
# we can't use django-user-account until upstream merge changes for geonode.
# this is temporary solution
https://github.com/cezio/django-user-accounts/archive/252_255_mixed.zip#egg=django-user-accounts-2.0.2
-e git://github.com/GeoNode/geonode.git#egg=geonode
